### PR TITLE
Missed case in assignment checking

### PR DESCRIPTION
**Pull request by zschutzman**
The stuff I wrote yesterday doesn't handle the case where all of the unit names are correct, but the assignment has some unit in more than one district. This checks for that problem as well.

### CODE REVIEW

**Comment by maxhully** [comment]
We should add tests covering these behaviors too.

**Comment by zschutzman** [comment]
I don't think that this last case is even reachable in the current setup, since the constructor inverts a dictionary of the form {vertex : assn}, and a vertex can't appear as a key more than once, so it will never be in two different sets in the reversed dictionary.  It may become an issue as more kinds of i/o are allowed and we need to worry about a user accidentally modifying the second column of a csv, for example.

I can write a test function to try the first two cases (not every vertex has an assignment; dictionary names are different from vertex names).

**Comment by maxhully** [comment]
Good point! Then we should probably rearrange things so that case raises an exception.

**Comment by zschutzman** [comment]
I wrote three test functions. The first two check that doing something bad with standard methods causes an error.  The third verifies that the `validate_assignment()` method is catching the case where some vertex belongs to more than one district, even though this is not reachable in the typical workflow.

**Pull request merged**
